### ISSUE TITLE
ypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by luciernag** [mohimanilab/NRPminer#2]
Hello, I'm trying to run NRPminer but an error appears :
Traceback (most recent call last):
  File "/data/ccms-gnps/tools/nrpminer/nrpminer/nrpminer.py", line 250, in <module>
    args.minAdomainscore, maxMod)
  File "/data/ccms-gnps/tools/nrpminer/nrpminer/scripts/create_putative_nrp_database_nrpspredictor3.py", line 572, in create_putative_nrp_dataset
    all_nrpspredictorCode_files_in_dir = glob.glob(nrpspks_predictions_dir+"/ctg*_nrpspredictor*_codes.txt")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Tool execution terminates abnormally with exit code [1]

Do you know how can I fix it?  the mistaje is related with the antiSMASH version?

Regards!

**Comment by GabrieleRigano99** [comment]
I have the same problem
